---
ocm-token: xxxXXXyyyYYYzzzZZZ           # Offline token for authentication.
ocm-token-url: https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
gateway-url: http://localhost:8000  # Gateway URL.
client:
  - id: cloud-services              # OpenID client identifier.
  - secret: "secure-secret"         # OpenID client secret.
aws:
  - region: "us-west-1"
    access-key: "ASD7ASFET65FFGHDFFS"
    secret-access-key: "fjhgsadf6#$!@%&/dfghdfgdsdf"
    account-id: "123434565665"
  - region: "us-west-2"
    access-key: "ASD7ASFET65FFGHDFFS"
    secret-access-key: "fjhgsadf6#$!@%&/dfghdfgdsdf"
    account-id: "123434565665"
elastic:
  server: "http://elastic.apps.perfscale.devcluster.openshift.com/"
  user: "user"
  password: "password"
  index: "es-index"
duration: 2
cooldown: 10
output-path: "./results"
rate: "5/s"
test-id: new-test
ramp-type: exponential
start-rate: 1
end-rate: 120
ramp-steps: 6
tests:
  self-access-token:
    rate: "1000/h"
    duration: 1
  list-subscriptions:
    rate: "2000/h"
    duration: 1
  access-review:
    rate: "100/s"
    duration: 1
  register-new-cluster:
    rate: "1000/h"
    duration: 1
  register-existing-cluster:
    rate: "25/s"
    duration: 1
  create-cluster:
    rate: "10/s"
    duration: 1
  list-clusters:
    rate: "10/s"
    duration: 1
  get-current-account:
    rate: "6/m"
    duration: 1
  quota-cost:
    rate: "1000/h"
    duration: 1
  resource-review:
    rate: "2000/h"
    duration: 1
  cluster-authorizations:
    duration: 30
    ramp-type: linear
    start-rate: 1
    end-rate: 50
    ramp-steps: 6
  self-terms-review:
    duration: 30
    ramp-type: exponential
    start-rate: 1
    end-rate: 50
    ramp-steps: 6
  certificates:
    rate: "2/s"
    duration: 1
